# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: pip
  directory: "/jupyter" # Path to the directory containing Pipfile and Pipfile.lock
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: "pip upgrade"
  allow:
    - dependency-type: all
  insecure-external-code: false
    - package-ecosystem: pip
  directory: "/rstudio" # Path to the directory containing Pipfile and Pipfile.lock
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: "pip upgrade"
  allow:
    - dependency-type: all
  insecure-external-code: false
    - package-ecosystem: pip
  directory: "/runtimes" # Path to the directory containing Pipfile and Pipfile.lock
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: "pip upgrade"
  allow:
    - dependency-type: all
  insecure-external-code: false
    - package-ecosystem: pip
  directory: "/cuda" # Path to the directory containing Pipfile and Pipfile.lock
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: "pip upgrade"
  allow:
    - dependency-type: all
  insecure-external-code: false
    - package-ecosystem: pip
  directory: "/codeserver" # Path to the directory containing Pipfile and Pipfile.lock
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: "pip upgrade"
  allow:
    - dependency-type: all
  insecure-external-code: false
  
