# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    ignore-patterns:
      - "requirements.txt"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "dependencies"
      - "security-vulnerability"
      - "{{severity}}"
    assignees:
      - "dibryant"
    commit-message:
      prefix: "pip"
      include: "scope"
